---
- name: "Ensure group {{ hadoop_group }} exists"
  group:
    name: "{{ hadoop_group }}"
    state: present

- name: Add User 
  user:
    name: "{{ hadoop_user}}"
    group: "{{ hadoop_group }}"
    home: "{{ hadoop_path }}"
    shell: /bin/bash
    append: yes
    state: present

- name: Check Public Key
  shell: "ls /home/{{ hadoop_user }}/.ssh|grep '.pub' |wc -l"
  register: key_exist
  ignore_errors: true

- name: Generate Public key
  user:
    name: "{{ hadoop_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: key_exist.stdout == '0'
